- Activation function
- 1.tanh(z)=e^z-e^-z/e^z+e^-z it take inout and convert it between -1 to 1
- but use sigmoid in output layer bcz it give the value  between 0 to 1
- in all other places try to use tanh
- issue with sigmoid and tanh
  - vanishing gradient problem the derivative bacomes 0 or nearby 0 and learning process slows down
- to overcome this problem we use ReLU
   - if your value is less than 0 then output will 0 and if more than output will same as the value
  - example if my value is -1 then i will get output as 0 and if my input is 3 then my output with relu is 3 only
  - for hidden layers if you are not sure which activation function to use, just use ReLu as your  Default choice
  - relu is very very lighweight function
  - it alsoo have vanishing gradient  problem for that it have leaky ReLU
  - Leaky ReLU(z)=max(0.1x,x)
  
  
  

In [1]:
import math
def sigmoid(x):
    return 1/(1+math.exp(-x))

In [2]:
sigmoid(100)

1.0

In [3]:
sigmoid(122)

1.0

In [4]:
sigmoid(-0.5)

0.3775406687981454

In [6]:
sigmoid(56)

1.0

In [10]:
def tenh(x):
    return(math.exp(x)-math.exp(-x))/(math.exp(x)+math.exp(-x))

In [11]:
tenh(-56)

-1.0

In [12]:
tenh(2)

0.964027580075817

In [13]:
def relu(x):
    return max(0,x)

In [14]:
relu(-10)

0

In [16]:
relu(3)

3

In [17]:
def leaky_relu(x):
    return max(0.1*x,x)

In [18]:
leaky_relu(8)

8

In [20]:
leaky_relu(-1)

-0.1

In [21]:
leaky_relu(-50)

-5.0

In [22]:
#hence sigmoid function renge 0 to 1
#tanh activation function range -1 to 1
#relu activation function ranges between 0 to infinity
#leaky rely activation function ranges between  -infinity to infinity


In [23]:
#we use this type of activation function from keras api and tensorflow

- Derivative vs slope
     - derivative is used for non linear euation        -slope is used for linear equation
     - derivative is function                                   -slope is constant

- partial derivative 
   - f(bedroom,square feet)=bedrooms^3+ square feet^2
   - so partial derivative will d(price)/d(bedroom)=3*bedroom^2
   - so it tells that how much a price is changing given a change in bedroom
   - d(price)/d(square feet)=2* sqr feet
   - how much a price is changing a given a change in square feet
 -for more information about partial derivative visit mathisfun.com

- matrics basics
  -when you have single row and single column so row and column is  called vector and multiplication between them is called 
  dot product 

In [24]:
import numpy as np


In [25]:
revenue=np.array([[1800,200,220],[24,36,40],[12,18,20]])
expanses=np.array([[80,90,100],[10,16,20],[8,10,10]])

In [27]:
#subtraction
profit=revenue-expanses
profit

array([[1720,  110,  120],
       [  14,   20,   20],
       [   4,    8,   10]])

In [33]:
price=np.array([1000,400,1200])
unitsales=np.array([[30,40,50],[5,10,15],[2,5,7]])

In [36]:
np.dot(price,unitsales)

array([[34400, 50000, 64400]])

In [39]:
#converting usd revenue onto indian ruppes
revenue_usd=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenue_inr=80*revenue_usd
revenue_inr

array([[16000, 17600, 20000],
       [ 5440,  6320,  8400],
       [ 8800, 11200, 14400],
       [ 6400,  6800,  7200]])

In [42]:
#calculate total flowers sale every month for flower shop
units_sold=np.array([[50,60,25],[10,13,5],[40,70,52]])
pricr_per_unit=np.array([20,30,15])

total_sales_Amount=np.dot(pricr_per_unit,units_sold)

In [43]:
total_sales_Amount


array([1900, 2640, 1430])